# Portainer-optimized Docker Compose file
# Use this file for Portainer deployment

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_prod
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:/X+K6OEClrSLDlq0zN8i4J1VGCKTnQa3j5/XSvEePSg=
      APP_URL: http://192.168.10.200:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: pixelip
      DB_PASSWORD: Kang@2k25
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - app_storage:/var/www/storage
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    container_name: laravel_db_prod
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M
    environment:
      MYSQL_ROOT_PASSWORD: Kang@2k25
      MYSQL_DATABASE: laravel
      MYSQL_USER: pixelip
      MYSQL_PASSWORD: Kang@2k25
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - dbdata:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3307:3306"
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pKang@2k25"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dbdata:
    driver: local
  app_storage:
    driver: local

networks:
  laravel_network:
    driver: bridge
