services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: laravel_minimal
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:/X+K6OEClrSLDlq0zN8i4J1VGCKTnQa3j5/XSvEePSg=
      APP_URL: http://192.168.10.200:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: pixelip
      DB_PASSWORD: Kang@2k25
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_minimal
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Kang@2k25
      MYSQL_DATABASE: laravel
      MYSQL_USER: pixelip
      MYSQL_PASSWORD: Kang@2k25
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
