version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:/X+K6OEClrSLDlq0zN8i4J1VGCKTnQa3j5/XSvEePSg=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: pixelip
      DB_PASSWORD: Kang@2k25

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    ports:
      - "3307:3306"  # Use 3307 to avoid conflict with local MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: pixelip
      MYSQL_PASSWORD: Kang@2k25
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
